Page({
  data:{
    name:'',
    type:'',
    chargePerson:'',
    phone:'',
    date:'',
    image:'',
    msg:'',
    activity:'',
    recruit:'',
    sponsor:'',
    other:''
  },
  onLoad:function(options){
    this.setData({
      name:options.name,
      type:options.type,
      chargePerson:options.chargePerson,
      phone:options.phone,
      date:options.date,
      image:options.image,
      msg:options.msg,
      activity:options.activity,
      recruit:options.recruit,
      sponsor:options.sponsor,
      other:options.other
    }) 
  }
})